[package]
name = "inference"
version = "0.1.0"
edition = "2023_10"

[dependencies]
linearregressor_coefficients = { path = "../attributes/linearregressor_coefficients"} 
linearregressor_intercepts = { path = "../attributes/linearregressor_intercepts"} 
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "7d84a42" } 
[lib]
sierra-text = true